### ISSUE TITLE
`npm run dev` throw errors

### ISSUE THREAD

**Issue by NehalHassan** [tharyckgusmao/React-Boillerplate-Easy#1]
the project isn't working.
when run npm install it gives me this warning.
` npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.`

after running npm run dev

```
/React-Boillerplate-Easy/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/React-Boillerplate-Easy/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/React-Boillerplate-Easy/node_modules/webpack-dev-server/bin/webpack-dev-server.js:86:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devida@1.0.0 dev: `chokidar=true NODE_ENV=development webpack-dev-server --mode=development --open --hot --config webpack/webpack.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devida@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
And one more thing,
the extract-text-webpack-plugin package is deprecated and no longer worked with webpack 4.
It would help  to switch from extract-text-webpack-plugin to [mini-css-extract-plugin  ](https://github.com/webpack-contrib/mini-css-extract-plugin)

**Comment by tharyckgusmao** [comment]
This project is with the version of the old packages and standards, I have not uploaded the recent version with everything updated. But it still works and only you install the right packages for it.

**Comment by NehalHassan** [comment]
:+1:
